name: Check Typst PDF Consistency

on:
  pull_request:
    paths: # Only run if .typ or .pdf files are changed
      - "**.typ"
      - "**.pdf"

jobs:
  check_pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate diff

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          version: "latest"

      - name: Install PDF comparison tool and xvfb
        id: install_pdf_tools # Give an ID to this step
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common xvfb # Add xvfb
          sudo add-apt-repository -y universe
          sudo apt-get update -y

          PDF_DIFF_CMD_NAME=""
          # Try installing 'diffpdf' (common on newer Ubuntu, e.g., 24.04 "noble")
          if sudo apt-get install -y diffpdf; then
            if command -v diffpdf &> /dev/null; then
              echo "Successfully installed 'diffpdf'."
              PDF_DIFF_CMD_NAME="diffpdf"
            fi
          fi

          # If 'diffpdf' wasn't found or failed, try 'diff-pdf' (common on older Ubuntu, e.g., 22.04 "jammy")
          # Note: 'diff-pdf' is typically a true CLI tool and might not need xvfb.
          # The logic here prioritizes 'diffpdf' if available.
          if [ -z "$PDF_DIFF_CMD_NAME" ]; then
            echo "'diffpdf' not found or installation failed. Attempting 'diff-pdf'..."
            if sudo apt-get install -y diff-pdf; then
              if command -v diff-pdf &> /dev/null; then
                echo "Successfully installed 'diff-pdf'."
                PDF_DIFF_CMD_NAME="diff-pdf"
              fi
            fi
          fi

          if [ -z "$PDF_DIFF_CMD_NAME" ]; then
            echo "::error::Neither 'diffpdf' nor 'diff-pdf' could be installed. Please check package availability for the runner's OS."
            exit 1
          else
            echo "Using '$PDF_DIFF_CMD_NAME' for PDF comparison."
            echo "pdf_diff_command=$PDF_DIFF_CMD_NAME" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get changed Typst files
        id: changed_typst_files
        run: |
          MERGE_BASE=$(git merge-base origin/${{ github.base_ref }} HEAD)
          echo "Comparing changes between $MERGE_BASE (base) and HEAD (current PR commit)"
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM $MERGE_BASE HEAD -- '*.typ')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No .typ files were added or modified in this PR."
            echo "changed_files_list=''" >> $GITHUB_OUTPUT
          else
            echo "Added or modified .typ files to check:"
            echo "$CHANGED_FILES"
            echo "changed_files_list<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Compile Typst and Compare PDFs
        if: steps.changed_typst_files.outputs.changed_files_list != ''
        env:
          PDF_DIFF_COMMAND: ${{ steps.install_pdf_tools.outputs.pdf_diff_command }}
        run: |
          FAILURE_DETECTED=0
          echo "Using PDF comparison command: ${{ env.PDF_DIFF_COMMAND }}"

          # Use process substitution to avoid subshell issues with FAILURE_DETECTED
          while IFS= read -r typ_file; do
            # Skip empty lines, if any (robustness)
            if [ -z "$typ_file" ]; then
              continue
            fi

            echo ""
            echo "--------------------------------------------------"
            echo "Processing: $typ_file"
            echo "--------------------------------------------------"

            committed_pdf_file="${typ_file%.typ}.pdf"
            temp_dir=$(mktemp -d)
            generated_pdf_file="$temp_dir/generated_$(basename "${typ_file%.typ}").pdf"

            echo "Expected committed PDF: $committed_pdf_file"
            echo "Path for newly generated PDF: $generated_pdf_file"

            if [ ! -f "$committed_pdf_file" ]; then
              echo "::error file=$typ_file,title=Missing PDF::Committed PDF '$committed_pdf_file' not found for Typst file '$typ_file'. Please ensure the PDF is compiled and included in the PR."
              FAILURE_DETECTED=1
              rm -rf "$temp_dir"
              continue
            fi

            echo "Compiling '$typ_file' to '$generated_pdf_file'..."
            if typst compile "$typ_file" "$generated_pdf_file"; then
              echo "Compilation successful."
            else
              echo "::error file=$typ_file,title=Typst Compilation Failed::Failed to compile Typst file '$typ_file'."
              FAILURE_DETECTED=1
              rm -rf "$temp_dir"
              continue
            fi

            echo "Comparing '$committed_pdf_file' with '$generated_pdf_file' using '${{ env.PDF_DIFF_COMMAND }}'..."
            # Prepend with xvfb-run if the command is 'diffpdf' (which is known to need it)
            # 'diff-pdf' (with hyphen) usually doesn't need it.
            COMPARISON_CMD=""
            if [ "${{ env.PDF_DIFF_COMMAND }}" = "diffpdf" ]; then
              COMPARISON_CMD="xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ${{ env.PDF_DIFF_COMMAND }}"
            else
              COMPARISON_CMD="${{ env.PDF_DIFF_COMMAND }}"
            fi

            # The $COMPARISON_CMD variable will be expanded by the shell here
            if $COMPARISON_CMD "$committed_pdf_file" "$generated_pdf_file"; then
              echo "✅ PDF '$committed_pdf_file' is up-to-date with '$typ_file'."
            else
              echo "::error file=$typ_file,title=PDF Out of Date::PDF '$committed_pdf_file' is not identical to the output of '$typ_file'. Please recompile '$typ_file' and commit the updated PDF."
              FAILURE_DETECTED=1
            fi
            rm -rf "$temp_dir"
          done < <(echo "${{ steps.changed_typst_files.outputs.changed_files_list }}") # End of process substitution

          echo "--------------------------------------------------"
          if [ "$FAILURE_DETECTED" -eq 1 ]; then
            echo "❌ PDF consistency check failed for one or more files."
            exit 1
          else
            echo "✅ All checked Typst files have up-to-date PDFs."
          fi
        shell: bash
